# Generated by Django 5.1.2 on 2024-10-17 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stundentWorksPlatform', '0002_alter_user_balance_alter_user_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewreports',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='reviewreports',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stundentWorksPlatform.review'),
            preserve_default=False,
        ),
    ]
