# Generated by Django 5.1.2 on 2024-10-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundentWorksPlatform', '0003_remove_reviewreports_reviewer_reviewreports_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='seller',
        ),
    ]
