# Generated by Django 5.1.2 on 2024-10-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stundentWorksPlatform', '0004_remove_purchase_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance_reduction',
        ),
    ]
